version: '3'

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - base_network
    ports:
      - 27017:27017
  api:
    container_name: pet_api
    image: node:8-alpine
    networks: 
      - base_network
    ports:
      - "3000:80"
    command: sh -c "npm install && npm run local"
    working_dir: /app
    volumes:
      - ./etec-presentation-api:/app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - base_network

networks:
  base_network: